"""V12.8 RAG-style business memory facade.

The facade still returns deterministic company baselines, but it also retrieves
approved/effective experience cards generated by completed recap cycles. Pending
review drafts are not used for task enhancement.
"""

from __future__ import annotations

from typing import Any, Dict

from src.services.action_authorization_gate_service import infer_action_type

RAG_BUSINESS_MEMORY_VERSION = "12.8.0"

BASELINES = {
    "default": {
        "minRoi": 2.0,
        "minGrossMarginRate": 0.28,
        "minSellableDays": 7,
        "refundRateCeiling": 0.12,
        "operatorActivityBudgetRange": [3000, 8000],
        "operatorWeightPermission": "middle",
    }
}

HISTORICAL_ACTION_MEMORY = {
    "activity_participation": {
        "trafficLiftRange": "1.15x-1.90x",
        "gmvLiftRange": "+12%-+70%",
        "roiChangeRange": "-8%-+12%",
        "inventoryConsumptionRange": "平日 1.3x-1.75x",
        "memoryRule": "真实活动复盘写入后，按平台、类目、价格带、资源位继续缩小估算范围。",
    },
    "title_test": {
        "clickRateLiftRange": "+3%-+15%",
        "conversionChangeRange": "-2%-+5%",
        "testWindowDays": 3,
        "memoryRule": "标题测试复盘后记录关键词、人群、平台和点击率变化。",
    },
    "main_image_test": {
        "clickRateLiftRange": "+3%-+15%",
        "conversionChangeRange": "-2%-+5%",
        "testWindowDays": 3,
        "memoryRule": "主图测试复盘后记录画面方向、卖点顺序和点击率/转化变化。",
    },
    "inventory_restock": {
        "sellableDaysFloor": 7,
        "restockReviewWindowDays": [3, 7],
        "memoryRule": "库存任务复盘后记录断货前可售天数、补货周期、活动/投放承接损失。",
    },
}


def _feedback(task: Dict[str, Any]) -> Dict[str, Any]:
    try:
        from src.services.rag_feedback_loop_service import retrieve_rag_feedback_for_task

        return retrieve_rag_feedback_for_task(task)
    except Exception as exc:
        return {"version": "12.8.0", "items": [], "matchedCount": 0, "error": str(exc), "rule": "RAG feedback retrieval failed closed."}


def business_memory_context(task: Dict[str, Any]) -> Dict[str, Any]:
    action_type = infer_action_type(task)
    feedback = _feedback(task)
    return {
        "version": RAG_BUSINESS_MEMORY_VERSION,
        "mode": "rag_business_policy_memory_and_feedback_loop",
        "actionType": action_type,
        "companyBaseline": BASELINES["default"],
        "historicalMemory": HISTORICAL_ACTION_MEMORY.get(action_type, {}),
        "approvedExperienceCards": feedback.get("items") or [],
        "approvedExperienceMatchedCount": feedback.get("matchedCount", 0),
        "feedbackLoop": feedback,
        "approvalPolicy": {
            "autoConfirmUsesConservativeFloor": True,
            "operatorProvidesFactsOnly": True,
            "managerApprovesWhenOverPermissionOrBelowBaseline": True,
        },
        "memoryWriteback": {
            "afterDays": 3,
            "targets": ["周报", "商品策略记录", "RAG记忆候选"],
            "metrics": ["ROI", "GMV/支付金额", "访客数", "点击率", "转化率", "广告消耗", "库存消耗", "退款率", "毛利率"],
            "rule": "只有自动复盘完成并通过人工审核的经验卡，才会被下一次任务生成召回。",
        },
    }


def apply_rag_business_memory(task: Dict[str, Any]) -> Dict[str, Any]:
    context = business_memory_context(task)
    return {**task, "ragBusinessMemory": context, "v126RagMemory": context}
