(function () {
  let notice = "";
  const s = (value) => AppShell.escape(value ?? "");
  function taskButton(item) {
    const task = AppTaskActions.findOpenTask(item);
    return task ? `<button type="button" data-open-task="${s(task.id)}" class="ghost">查看任务</button><button type="button" data-task-report="${s(task.id)}">任务报告</button>` : `<button type="button" data-candidate-report="competitor:${s(item.id)}">查看信号</button>`;
  }
  function row(item) {
    return `<article class="competitor-row"><div class="competitor-title-cell"><div class="competitor-thumb">${s(item.imageLabel)}</div><div class="competitor-title-block"><strong>${s(item.title)}</strong><small>${s(item.platform)} · ${s(item.store)}</small><span>对应商品：${s(item.targetProduct)}</span></div></div><div class="competitor-metric-strip"><div class="competitor-number-cell"><span>价格变化</span><strong>${s(item.pricePosition)}</strong><small>不直接跟价</small></div><div class="competitor-number-cell warning"><span>差评关键词</span><strong>${s(item.badReview)}</strong><small>可转测试假设</small></div><div class="competitor-number-cell ${item.status === "风险" ? "danger" : "good"}"><span>机会点</span><strong>${s(item.status)}</strong><small>${s(item.opportunity)}</small></div></div><div class="competitor-actions">${taskButton(item)}</div></article>`;
  }
  window.CompetitorPage = { route: "business-competitors", title: "竞品信号", render() { return `<section class="competitor-toolbar"><div><p class="eyebrow">COMPETITOR SIGNALS · V11.1</p><h2>竞品信号列表</h2><p>竞品模块是机会池，承接价格变化、差评关键词和可转化上新机会；不直接跳任务栏。</p></div></section>${notice ? AppShell.notice("操作结果", notice) : ""}<section class="page-section competitor-list-section"><div class="section-header"><h3>竞品信号</h3><span class="status-badge">${AppMockData.competitors.length} 个观察对象</span></div><div class="competitor-card-list">${AppMockData.competitors.map(row).join("")}</div></section>`; }, mount(ctx) { ctx.delegate("[data-open-task]", "click", (_, node) => AppTaskActions.openTodoTask(node.dataset.openTask)); ctx.delegate("[data-task-report]", "click", (_, node) => AppTaskActions.openTaskReport(node.dataset.taskReport)); ctx.delegate("[data-candidate-report]", "click", (_, node) => { const [module, id] = node.dataset.candidateReport.split(":"); AppTaskActions.openCandidateReport(module, id); }); ctx.addCleanup(AppTaskStore.subscribe(() => AppRouter.schedule("task-store"))); } };
})();