"""V22.4 public release with V22.5.11 deterministic data-lineage deployment."""
from __future__ import annotations

VERSION = "22.4.0"
API_VERSION = VERSION
PRODUCT_VERSION = VERSION
RELEASE_VERSION = VERSION
CONTRACT_VERSION = VERSION
RELEASE_IDENTITY_VERSION = VERSION
RELEASE_MANIFEST_VERSION = "release.manifest.v1"
RUNTIME_MODE = "single_release_sealed_runtime"
RELEASE_PYTHON_VERSION = "3.11.9"

DEPLOYMENT_SINGLE_AUTHORITY_VERSION = "22.5.4"
DEPLOYMENT_DATABASE_LINEAGE_VERSION = "22.5.11"
RUNTIME_DATABASE_SCHEMA_PREP_VERSION = DEPLOYMENT_DATABASE_LINEAGE_VERSION
ROLLBACK_DATABASE_RESTORE_VERSION = DEPLOYMENT_DATABASE_LINEAGE_VERSION
THREE_AGENT_RESPONSIBILITY_VERSION = "22.5.0"
THREE_AGENT_PIPELINE_VERSION = "22.5.5"
AGENT1_EXECUTION_LOCK_VERSION = THREE_AGENT_PIPELINE_VERSION
AGENT2_DRAFT_RUNTIME_VERSION = THREE_AGENT_PIPELINE_VERSION
AGENT3_SOP_RUNTIME_VERSION = THREE_AGENT_PIPELINE_VERSION
TASK_MAPPING_RUNTIME_VERSION = THREE_AGENT_PIPELINE_VERSION
COMPANY_SOP_RAG_CONTEXT_VERSION = THREE_AGENT_PIPELINE_VERSION
PIPELINE_LIVE_CONTRACT_VERSION = "22.5.9"

AGENT1_INPUT_SEMANTIC_VERSION = "22.5.8"
AGENT1_INPUT_SCHEMA_VERSION = "agent_input.agent1.v3"
AGENT1_SOURCE_LINEAGE_VERSION = AGENT1_INPUT_SEMANTIC_VERSION
AGENT1_OUTPUT_NORMALIZATION_VERSION = AGENT1_INPUT_SEMANTIC_VERSION

HASH_DIRECTED_ARTIFACT_RUNTIME_VERSION = "22.5.9"
AGENT_EXECUTION_INDEX_VERSION = HASH_DIRECTED_ARTIFACT_RUNTIME_VERSION
AGENT_BATCH_MANIFEST_VERSION = HASH_DIRECTED_ARTIFACT_RUNTIME_VERSION
ACTIVE_LLM_INPUT_PROJECTION_VERSION = HASH_DIRECTED_ARTIFACT_RUNTIME_VERSION
AGENT1_TOKEN_RUNTIME_VERSION = HASH_DIRECTED_ARTIFACT_RUNTIME_VERSION
AGENT1_HARD_INTERFACE_VERSION = HASH_DIRECTED_ARTIFACT_RUNTIME_VERSION
STATION_AGENT_WORKER_ACTIVE_VERSION = HASH_DIRECTED_ARTIFACT_RUNTIME_VERSION
FRONTEND_VIEW_ARTIFACT_VERSION = HASH_DIRECTED_ARTIFACT_RUNTIME_VERSION
FRONTEND_VIEW_MANIFEST_VERSION = HASH_DIRECTED_ARTIFACT_RUNTIME_VERSION
FRONTEND_CACHE_CONTRACT_VERSION = HASH_DIRECTED_ARTIFACT_RUNTIME_VERSION

INTERFACE_DOCUMENTATION_VERSION = "22.5.10"
API_SELF_DESCRIPTION_VERSION = INTERFACE_DOCUMENTATION_VERSION
CANONICAL_INTERFACE_DOCUMENT = "docs/V22.5.9_INTERFACE_AND_MIGRATION.md"
STABLE_WORKER_IMPORT = "src.services.station_agent_worker_v2255_service"
ACTIVE_WORKER_IMPLEMENTATION = "src.services.station_agent_worker_v2259_service"
STABLE_HARD_INTERFACE_FACADE = "src.services.agent_runtime_hard_interface_v2255_service"
ACTIVE_AGENT1_TOKEN_IMPLEMENTATION = (
    "src.services.agent_token_runtime_hash_exact_v2259_service"
)
AGENT_EXECUTION_INDEX_NAME = "artifact_execution_index_v2259"
AGENT_BATCH_MANIFEST_CONTRACT = "agent_batch_manifest.v2259"
FRONTEND_VIEW_MANIFEST_CONTRACT = "frontend_view.manifest.v2259"
FRONTEND_VIEW_MODULE_CONTRACT = "frontend_view.module.v2259"

FRONTEND_EXPERIENCE_VERSION = "22.5.6"
PRODUCT_DETAIL_COMPOSITE_VERSION = FRONTEND_EXPERIENCE_VERSION
REPORT_PIPELINE_UI_VERSION = "22.5.8"

REPORT_BATCH_VERSION = VERSION
OPERATING_EVIDENCE_VERSION = VERSION
OBSERVATION_MATURITY_VERSION = VERSION
EXPERIMENT_ADMISSION_VERSION = VERSION
AGENT1_EXPERIMENT_POLICY_VERSION = VERSION
AGENT2_EXPERIMENT_POLICY_VERSION = VERSION
AGENT1_OBSERVATION_CONTRACT_VERSION = VERSION
PRODUCT_TREND_READ_MODEL_VERSION = VERSION
AGENT_ENTRY_INTERFACE_VERSION = VERSION
STATION_INTERFACE_VERSION = VERSION
SINGLE_ACTION_INTERFACE_VERSION = VERSION
PIPELINE_LIVE_INTERFACE_VERSION = VERSION
SIGNAL_POOL_VERSION = VERSION
SIGNAL_RUNTIME_SEAL_VERSION = VERSION
RUNTIME_GOVERNANCE_VERSION = VERSION
LLM_PROVIDER_VERSION = VERSION
LLM_COST_GOVERNANCE_VERSION = VERSION
ACTION_PLAN_IR_VERSION = VERSION
ACTION_AUTHORITY_VERSION = VERSION
TASK_DETAIL_PROJECTION_VERSION = VERSION
TASK_METRIC_EVIDENCE_PROJECTION_VERSION = VERSION
DASHBOARD_EXPERIENCE_VERSION = VERSION
NEURAL_OPERATING_UI_VERSION = VERSION
NEURAL_OPERATING_READ_MODEL_VERSION = VERSION
OPERATOR_GROWTH_PROJECTION_VERSION = VERSION
AGENT2_PROVENANCE_VERSION = VERSION
AGENT2_LEASE_VERSION = VERSION
AGENT2_FAILURE_GOVERNANCE_VERSION = VERSION
AGENT2_CONTRACT_ALIGNMENT_VERSION = VERSION
INVENTORY_ACTION_GUARD_VERSION = VERSION
AGENT2_POLICY_SHAPE_RECOVERY_VERSION = VERSION
BUDGET_GOVERNANCE_VERSION = VERSION
AGENT2_FINAL_CONTRACT_REBUILD_VERSION = VERSION
SOP_MAPPING_RUNTIME_FIX_VERSION = VERSION
AGENT2_SINGLE_ACTION_CONTRACT_VERSION = VERSION
METRIC_DIGEST_VERSION = VERSION
ACTIVE_ACTION_CONTRACT_VERSION = VERSION
AGENT_SEMANTIC_VERSION = VERSION
CONTEXTUAL_AGENT_RUNTIME_VERSION = VERSION
AGENT1_DECISION_IR_VERSION = VERSION
AGENT1_DIAGNOSTIC_RAG_VERSION = VERSION
AGENT2_AUTONOMOUS_PLAN_VERSION = AGENT2_DRAFT_RUNTIME_VERSION
AUTONOMOUS_SOP_RUNTIME_VERSION = AGENT3_SOP_RUNTIME_VERSION

LLM_INPUT_PROJECTION_VERSION = "22.2.0"
SEMANTIC_CONTINUITY_CONTRACT_VERSION = "22.2.0"
ARTIFACT_REPOSITORY_VERSION = "22.2.1"
ARTIFACT_STORAGE_VERSION = "22.2.1"
ARTIFACT_REGISTRY_VERSION = "22.2.1"
ARTIFACT_LINEAGE_VERSION = "22.2.1"
PIPELINE_ARTIFACT_DUAL_WRITE_VERSION = "22.2.1"
PUBLIC_TASK_DTO_VERSION = "22.2.3"
PIPELINE_REFERENCE_RUNTIME_VERSION = "22.2.4"
PIPELINE_PAYLOAD_RETIREMENT_VERSION = "22.2.4"
OPERATING_EVIDENCE_CONTRACT_VERSION = "21.5.0"
STATION_TRUTH_CONTRACT_VERSION = "22.2.5"
STATION_QUEUE_TRUTH_VERSION = "22.2.5"
STATION_BUSINESS_ARTIFACT_VERSION = "22.2.5"
ARTIFACT_SIGNAL_ADMISSION_VERSION = "22.2.6"
END_TO_END_AGENT_FLOW_VERSION = "22.2.6"
AGENT1_ARTIFACT_RUNTIME_VERSION = "22.2.6"
SIGNAL_ADMISSION_POLICY_VERSION = "22.2.6"
PIPELINE_TRUTH_READ_MODEL_VERSION = "22.2.6"
AGENT_RUNTIME_RECOVERY_VERSION = "22.2.6.1"
DEPLOYMENT_BACKUP_LIFECYCLE_VERSION = "22.2.6.2"
AGENT_RUNTIME_NATIVE_VERSION = "22.2.6.3"
HARD_INTERFACE_BRIDGE_VERSION = "22.3.0.1"

ARTIFACT_TRANSPORT_VERSION = "22.3.0"
PIPELINE_ARTIFACT_CONTRACT_VERSION = "22.3.0"
AGENT_INPUT_CONTRACT_VERSION = "22.3.0"
AGENT_INPUT_TRANSPORT_VERSION = "22.3.0"
AGENT_TOKEN_RUNTIME_VERSION = "22.3.0"
AGENT_RUNTIME_HARD_INTERFACE_VERSION = "22.3.0"
STATION_AGENT_WORKER_VERSION = VERSION


def runtime_versions() -> dict[str, object]:
    return {
        "api": VERSION,
        "product": VERSION,
        "release": VERSION,
        "contract": VERSION,
        "runtimeMode": RUNTIME_MODE,
        "releaseIdentity": RELEASE_IDENTITY_VERSION,
        "releaseManifest": RELEASE_MANIFEST_VERSION,
        "releasePython": RELEASE_PYTHON_VERSION,
        "deploymentSingleAuthority": DEPLOYMENT_SINGLE_AUTHORITY_VERSION,
        "deploymentDatabaseLineage": DEPLOYMENT_DATABASE_LINEAGE_VERSION,
        "runtimeDatabaseSchemaPreparation": RUNTIME_DATABASE_SCHEMA_PREP_VERSION,
        "rollbackDatabaseRestore": ROLLBACK_DATABASE_RESTORE_VERSION,
        "threeAgentResponsibilityModel": THREE_AGENT_RESPONSIBILITY_VERSION,
        "threeAgentPipeline": THREE_AGENT_PIPELINE_VERSION,
        "stateMachineVersion": THREE_AGENT_PIPELINE_VERSION,
        "agent1ExecutionLock": AGENT1_EXECUTION_LOCK_VERSION,
        "agent1InputSemantic": AGENT1_INPUT_SEMANTIC_VERSION,
        "agent1InputSchema": AGENT1_INPUT_SCHEMA_VERSION,
        "agent1SourceLineage": AGENT1_SOURCE_LINEAGE_VERSION,
        "agent1OutputNormalization": AGENT1_OUTPUT_NORMALIZATION_VERSION,
        "hashDirectedArtifactRuntime": HASH_DIRECTED_ARTIFACT_RUNTIME_VERSION,
        "agentExecutionIndex": AGENT_EXECUTION_INDEX_VERSION,
        "agentExecutionIndexName": AGENT_EXECUTION_INDEX_NAME,
        "agentBatchManifest": AGENT_BATCH_MANIFEST_VERSION,
        "agentBatchManifestContract": AGENT_BATCH_MANIFEST_CONTRACT,
        "activeLlmInputProjection": ACTIVE_LLM_INPUT_PROJECTION_VERSION,
        "agent1TokenRuntime": AGENT1_TOKEN_RUNTIME_VERSION,
        "agent1HardInterface": AGENT1_HARD_INTERFACE_VERSION,
        "activeStationAgentWorker": STATION_AGENT_WORKER_ACTIVE_VERSION,
        "frontendViewArtifact": FRONTEND_VIEW_ARTIFACT_VERSION,
        "frontendViewManifest": FRONTEND_VIEW_MANIFEST_VERSION,
        "frontendViewManifestContract": FRONTEND_VIEW_MANIFEST_CONTRACT,
        "frontendViewModuleContract": FRONTEND_VIEW_MODULE_CONTRACT,
        "frontendCacheContract": FRONTEND_CACHE_CONTRACT_VERSION,
        "interfaceDocumentation": INTERFACE_DOCUMENTATION_VERSION,
        "apiSelfDescription": API_SELF_DESCRIPTION_VERSION,
        "canonicalInterfaceDocument": CANONICAL_INTERFACE_DOCUMENT,
        "stableWorkerImport": STABLE_WORKER_IMPORT,
        "activeWorkerImplementation": ACTIVE_WORKER_IMPLEMENTATION,
        "stableHardInterfaceFacade": STABLE_HARD_INTERFACE_FACADE,
        "activeAgent1TokenImplementation": ACTIVE_AGENT1_TOKEN_IMPLEMENTATION,
        "artifactTransport": ARTIFACT_TRANSPORT_VERSION,
        "pipelineArtifactContract": PIPELINE_ARTIFACT_CONTRACT_VERSION,
        "agentInputContract": AGENT_INPUT_CONTRACT_VERSION,
        "agentInputTransport": AGENT_INPUT_TRANSPORT_VERSION,
        "agentTokenRuntime": AGENT_TOKEN_RUNTIME_VERSION,
        "agentRuntimeHardInterface": AGENT_RUNTIME_HARD_INTERFACE_VERSION,
        "stationAgentWorker": STATION_AGENT_WORKER_VERSION,
        "stableAgentTokenFacadeContract": AGENT_TOKEN_RUNTIME_VERSION,
        "stableAgentRuntimeFacadeContract": AGENT_RUNTIME_HARD_INTERFACE_VERSION,
        "stationAgentWorkerPublic": STATION_AGENT_WORKER_VERSION,
        "hardInterfaceBridge": HARD_INTERFACE_BRIDGE_VERSION,
        "publicTaskDto": PUBLIC_TASK_DTO_VERSION,
        "operatingEvidenceContract": OPERATING_EVIDENCE_CONTRACT_VERSION,
        "stationTruthContract": STATION_TRUTH_CONTRACT_VERSION,
        "agent1JudgmentRuntime": AGENT1_TOKEN_RUNTIME_VERSION,
        "agent2DraftRuntime": AGENT2_DRAFT_RUNTIME_VERSION,
        "agent3SopRuntime": AGENT3_SOP_RUNTIME_VERSION,
        "taskMappingRuntime": TASK_MAPPING_RUNTIME_VERSION,
        "companySopRagContext": COMPANY_SOP_RAG_CONTEXT_VERSION,
        "pipelineLiveContract": PIPELINE_LIVE_CONTRACT_VERSION,
        "frontendExperience": FRONTEND_EXPERIENCE_VERSION,
        "productDetailComposite": PRODUCT_DETAIL_COMPOSITE_VERSION,
        "reportPipelineUi": REPORT_PIPELINE_UI_VERSION,
        "agentInputSchemas": {
            "agent1": AGENT1_INPUT_SCHEMA_VERSION,
            "agent2Draft": "agent_input.agent2_draft.v1",
            "agent3Sop": "agent_input.agent3_sop.v1",
        },
        "deploymentDataContracts": {
            "schemaPreparedBeforeLineage": True,
            "schemaPreparationIdempotenceRequired": True,
            "postStartSchemaHashMustMatchPreparedHash": True,
            "rollbackDatabaseBackupRestoreRequired": True,
            "rollbackLineageRestoreRequired": True,
            "rollbackServiceHealthVerificationRequired": True,
        },
        "hashDirectedContracts": {
            "oneExecutionHashOneAcceptedOutputRef": True,
            "cachedBusinessOutputRebindingAllowed": False,
            "legacyItemCacheOwnsBusinessReplay": False,
            "batchItemIdentity": "itemExecutionId+inputContentHash",
            "agent1MicrobatchSize": 8,
            "onlyTrueMissingItemsRetry": True,
            "frontendHead": "manifestHash",
            "frontendModuleIdentity": "moduleContentHash",
            "crossDataVersionViewFallbackAllowed": False,
        },
        "agent1StatusContracts": {
            "providerStatus": "provider transport only",
            "exactIdentityStatus": "itemExecutionId+inputContentHash validation",
            "normalizationStatus": "decision/output normalization only",
            "sourceValidationStatus": "sourceLineageValidation only",
            "decisionContractStatus": "observe/act and execution-lock contract",
        },
        "preservedContracts": {
            "llmInputProjection": LLM_INPUT_PROJECTION_VERSION,
            "semanticContinuity": SEMANTIC_CONTINUITY_CONTRACT_VERSION,
            "artifactRepository": ARTIFACT_REPOSITORY_VERSION,
            "artifactStorage": ARTIFACT_STORAGE_VERSION,
            "artifactRegistry": ARTIFACT_REGISTRY_VERSION,
            "artifactLineage": ARTIFACT_LINEAGE_VERSION,
            "pipelineReferenceRuntime": PIPELINE_REFERENCE_RUNTIME_VERSION,
            "pipelinePayloadRetirement": PIPELINE_PAYLOAD_RETIREMENT_VERSION,
            "artifactSignalAdmission": ARTIFACT_SIGNAL_ADMISSION_VERSION,
            "endToEndAgentFlow": END_TO_END_AGENT_FLOW_VERSION,
            "agentRuntimeRecovery": AGENT_RUNTIME_RECOVERY_VERSION,
            "agentRuntimeNative": AGENT_RUNTIME_NATIVE_VERSION,
        },
    }
